// Put your BQ info here
const PROJECT_ID = ''
const DATASET_NAME = ''
const TRANSACTION_TABLE_NAME = ''
const LEDGER_TABLE_NAME = ''

module.exports = {
  PROJECT_ID: PROJECT_ID,
  DATASET_NAME: DATASET_NAME,
  TRANSACTION_TABLE_NAME: TRANSACTION_TABLE_NAME,
  LEDGER_TABLE_NAME: LEDGER_TABLE_NAME,
}
